---
driver:
  name: vagrant

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[baryon::default]
    attributes:
      baryon:
        github_org: <%= ENV.fetch('BARYON_ORG', 'badorg') %>
        github_api_token: <%= ENV.fetch('BARYON_TOKEN', 'badtoken') %>
